INFERANALYZE = '/home/osboxes/infer/infer-linux64-v0.14.0/infer/bin/infer-analyze' --no-report --results-dir '/home/osboxes/experiments/openssl-OpenSSL_1_0_0l/infer-out' 

CLUSTERS=

default: test

all: test

test: $(CLUSTERS)
	@echo


clean:
	rm -f $(CLUSTERS)
