INFERANALYZE = '/home/osboxes/infer/infer-linux64-v0.14.0/infer/bin/infer-analyze' --no-report --results-dir '/home/osboxes/experiments/sqlite-version-3.6.10/bld/infer-out' 

CLUSTERS=

default: test

all: test

test: $(CLUSTERS)
	@echo


clean:
	rm -f $(CLUSTERS)
